### ISSUE TITLE
Improper gravity

### ISSUE THREAD

**Issue by mauro-merconchini** [anthonymendez/Cart-Duty#18]
We need to tweak the values concerning gravity and the weight of the player and the cart. This is especially apparent when getting off one of the ramps, as both the player and cart drift in the air before finally settling down.

**Comment by anthonymendez** [comment]
The drifting in the air is due to the velocity limit placed on the player. Need to ew implement movement so that when the player is above 5m/s or whatever the speed limit is, he will no longer add a force to his own movement and to the cart as well.
